Add bazel-cache chart
cgi-eoss/cgici-charts pull request #1
Opened 2018-04-30 11:30 UTC by Aphadion

Bazel cache chart derived from docker image at [buchgr/bazel-remote](https://github.com/buchgr/bazel-remote).

2018-05-02 14:27 UTC, Zetten requested changes

2018-05-02 14:27 UTC, Zetten commented on bazel-cache/templates/deployment.yaml
> +              mountPath: /data
The container needs to be started with arguments to configure the bazel-remote service. At a minimum `--max_size=<PVC size>` but a generic value array and matching iterator here for custom startup args would be useful too.

2018-05-04 14:18 UTC, Aphadion commented
I made the requested changes and the chart seems to deploy fine. I have a strong feeling that I've misused the way you're meant to amend commits on GitHub but there we are...

2018-05-04 15:54 UTC, Zetten requested changes

2018-05-04 15:54 UTC, Zetten commented on bazel-cache/values.yaml
> +#tls_key_file: ""
These values aren't used in the chart, but the fact they're here implies they could be. You could omit them and just leave `extraArgs`.

2018-05-04 15:54 UTC, Zetten commented on bazel-cache/values.yaml
> +## Additional command line arguments to pass to nginx-ingress-controller
Our chart isn't nginx-ingress-controller

2018-05-04 15:54 UTC, Zetten commented on bazel-cache/values.yaml
> +extraArgs: {}
Maybe add a comment linking to https://github.com/buchgr/bazel-remote/ so people can look up what args are available.

2018-05-04 15:54 UTC, Zetten commented on bazel-cache/templates/deployment.yaml
> +          {{- end }}
I'm not sure this is the neatest or easiest way to do it. Maybe just expect an array of strings, not a dict, and do:
```
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 10 }}
{{- end }}
```
(from https://github.com/kubernetes/charts/blob/master/stable/kubernetes-dashboard/templates/deployment.yaml#L35 - check the indent as well)

2018-05-04 16:48 UTC, closed without merging